project:
  type: "website"
  title: "mysite"
  output-dir: docs
  render:
    - "index.qmd"
    - "about.qmd"
    - "/analysis/2024*.qmd"
    - "/gofig/plot*.qmd"
    - "!code/"
    - "!data/"
    - "!output"

website:
  title: "mysite"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    # logo: assets/logo.png
    background: "light"
    search: true
      # - menu:
      #   - href: analysis/analysis1.qmd
      #     text: analysis
  # open-graph: true
  # twitter-card: 
  #   title: twitter
  #   site: "@chaodai"
  # comments: 
  #   hypothesis:
  #     theme: classic
  #     openSidebar: false
format:
  html:
    theme: yeti
    css: styles.css
